/// # BBS+ Linkability Control — Issue #1294
///
/// ## Problem
/// When the same BBS+ credential attributes are disclosed repeatedly to the
/// same or different verifiers, a passive observer that can correlate multiple
/// proofs may link them back to the same holder — even without learning the
/// hidden attributes — by:
/// 1. Tracking which `disclosed_fields` combinations appear together.
/// 2. Noticing that the `challenge` scalar correlates with the verifying key
///    and the same disclosed values.
/// 3. (For weak nonce schemes) replaying a captured proof against a different
///    verifier session.
///
/// ## Solution
/// This module provides *nonce-based unlinkability*:
/// - Every presentation uses a fresh, unpredictable `presentation_context`
///   (nonce) so the Fiat-Shamir challenge is unique per session.
/// - `generate_nonce` produces a 32-byte cryptographically secure nonce from
///   the system RNG.  Verifiers generate nonces; holders bind their proof to
///   that nonce.
/// - `create_unlinkable_disclosure` wraps `BbsPresentation::create_presentation`
///   with explicit nonce threading and an included nonce commitment so that
///   verifiers can confirm the proof was bound to *their* nonce.
/// - `verify_unlinkable_disclosure` verifies the proof and checks that the
///   embedded nonce matches the expected value — rejecting replays.
///
/// ## Privacy guarantees
/// 1. **Per-session unlinkability**: two proofs for the same credential
///    presented with different nonces share no observable scalar or point
///    (A_bar, B_bar, D are freshly randomized each call).
/// 2. **Nonce binding**: a proof cannot be replayed against a different nonce
///    because the Fiat-Shamir challenge incorporates the presentation context.
/// 3. **Verifier separation**: a proof created for verifier A cannot be
///    verified by verifier B if they use different nonces.
/// 4. **Hidden attribute privacy**: disclosed fields are bounded to exactly
///    the indices the holder chose; hidden attributes are protected by the
///    Schnorr responses.
///
/// ## Limitations
/// - This module cannot prevent linkability by *disclosed content itself*
///   (e.g. disclosing a unique identifier every time).  Holders should
///   minimise what they disclose.
/// - Nonce freshness depends on the verifier supplying a new nonce per
///   session; stale or repeated verifier nonces reduce the unlinkability
///   guarantee.
///
/// ## Issue requirements mapping
/// - "Implement nonce generation for unlinkable disclosures" → `generate_nonce`
/// - "Add `create_unlinkable_disclosure(env, credential_id, attributes, nonce)`"
///   → `create_unlinkable_disclosure`
/// - "Implement verification with nonce checking" →
///   `verify_unlinkable_disclosure`
/// - "Add privacy guarantee documentation" → this module doc

extern crate alloc;

use alloc::collections::BTreeMap;
use alloc::vec::Vec;

use crate::errors::{BbsError, BbsResult};
use crate::presentation::{BbsPresentation, PresentationProof};
use crate::primitives::Fr;
use crate::signature::{BbsSignature, VerifyingKey};

// ────────────────────────────────────────────────────────────────────────────
// Nonce generation

/// Generate a 32-byte cryptographically secure nonce.
///
/// The nonce MUST be generated by the *verifier* and transmitted to the
/// *holder* before the holder creates a proof.  Using a verifier-issued nonce
/// ensures that the proof is bound to one specific verifier session and cannot
/// be replayed by a third party.
///
/// The nonce is derived from the OS RNG via `rand::RngCore`, which on targets
/// that support it calls `getrandom`.  On `no_std` targets without OS RNG
/// support, the caller must supply their own RNG (see `generate_nonce_with_rng`).
#[cfg(feature = "std")]
pub fn generate_nonce() -> BbsResult<[u8; 32]> {
    let mut rng = rand::rngs::OsRng;
    generate_nonce_with_rng(&mut rng)
}

/// Generate a 32-byte nonce using a caller-supplied RNG.
///
/// Useful for `no_std` environments where `OsRng` is unavailable, or in
/// tests where deterministic nonces are required.
pub fn generate_nonce_with_rng<R: rand::RngCore>(rng: &mut R) -> BbsResult<[u8; 32]> {
    let scalar = Fr::random(rng);
    let bytes = scalar.to_bytes();
    Ok(bytes)
}

// ────────────────────────────────────────────────────────────────────────────
// Unlinkable disclosure envelope

/// The result of `create_unlinkable_disclosure`.
///
/// Contains the standard-format presentation proof bytes *plus* the nonce
/// that was bound into it, so verifiers can apply `verify_unlinkable_disclosure`
/// without separately tracking the nonce.
#[derive(Clone, Debug)]
pub struct UnlinkableDisclosure {
    /// Standard-format `PresentationProof` bytes (as produced by
    /// `PresentationProof::to_bytes()`).
    pub proof_bytes: Vec<u8>,
    /// The 32-byte nonce that was used as the `presentation_context`.
    pub nonce: [u8; 32],
    /// The credential identifier supplied by the caller (opaque bytes).
    pub credential_id: Vec<u8>,
    /// The revealed attribute indices included in this disclosure.
    pub disclosed_indices: Vec<u32>,
}

impl UnlinkableDisclosure {
    /// Deserialize the inner proof.
    pub fn proof(&self) -> BbsResult<PresentationProof> {
        PresentationProof::from_bytes(&self.proof_bytes)
    }

    /// Serialize to bytes for transport/storage.
    ///
    /// Wire format:
    /// ```text
    /// [32 bytes]  nonce
    /// [4 bytes]   credential_id length (LE u32)
    /// [N bytes]   credential_id
    /// [4 bytes]   disclosed_indices count (LE u32)
    /// [4*k bytes] disclosed_indices (each LE u32)
    /// [4 bytes]   proof_bytes length (LE u32)
    /// [M bytes]   proof_bytes
    /// ```
    pub fn to_bytes(&self) -> Vec<u8> {
        let mut out = Vec::new();
        out.extend_from_slice(&self.nonce);

        let cid_len = self.credential_id.len() as u32;
        out.extend_from_slice(&cid_len.to_le_bytes());
        out.extend_from_slice(&self.credential_id);

        let idx_count = self.disclosed_indices.len() as u32;
        out.extend_from_slice(&idx_count.to_le_bytes());
        for &idx in &self.disclosed_indices {
            out.extend_from_slice(&idx.to_le_bytes());
        }

        let proof_len = self.proof_bytes.len() as u32;
        out.extend_from_slice(&proof_len.to_le_bytes());
        out.extend_from_slice(&self.proof_bytes);

        out
    }

    /// Deserialize from bytes produced by `to_bytes`.
    pub fn from_bytes(bytes: &[u8]) -> BbsResult<Self> {
        if bytes.len() < 32 + 4 {
            return Err(BbsError::DeserializationError);
        }
        let mut off = 0usize;

        let mut nonce = [0u8; 32];
        nonce.copy_from_slice(&bytes[off..off + 32]);
        off += 32;

        let cid_len = read_u32(bytes, &mut off)? as usize;
        if off + cid_len > bytes.len() {
            return Err(BbsError::DeserializationError);
        }
        let credential_id = bytes[off..off + cid_len].to_vec();
        off += cid_len;

        let idx_count = read_u32(bytes, &mut off)? as usize;
        let mut disclosed_indices = Vec::with_capacity(idx_count);
        for _ in 0..idx_count {
            disclosed_indices.push(read_u32(bytes, &mut off)?);
        }

        let proof_len = read_u32(bytes, &mut off)? as usize;
        if off + proof_len > bytes.len() {
            return Err(BbsError::DeserializationError);
        }
        let proof_bytes = bytes[off..off + proof_len].to_vec();

        Ok(UnlinkableDisclosure {
            proof_bytes,
            nonce,
            credential_id,
            disclosed_indices,
        })
    }
}

fn read_u32(bytes: &[u8], offset: &mut usize) -> BbsResult<u32> {
    if *offset + 4 > bytes.len() {
        return Err(BbsError::DeserializationError);
    }
    let mut buf = [0u8; 4];
    buf.copy_from_slice(&bytes[*offset..*offset + 4]);
    *offset += 4;
    Ok(u32::from_le_bytes(buf))
}

// ────────────────────────────────────────────────────────────────────────────
// Public API

/// Create an unlinkable selective-disclosure proof.
///
/// This is the primary entry point for issue #1294.  It wraps
/// `BbsPresentation::create_presentation` with:
/// 1. Nonce threading — the `nonce` is used as the `presentation_context` so
///    that the Fiat-Shamir challenge is unique per session.
/// 2. Fresh r1/r2 randomization (handled by `create_presentation`) — ensures
///    A_bar, B_bar, D differ even for repeat disclosures of the same credential.
/// 3. An `UnlinkableDisclosure` envelope that bundles proof + nonce for the
///    verifier.
///
/// # Arguments
/// - `rng`              — caller-supplied RNG (must be cryptographically
///                        secure in production).
/// - `credential_id`    — opaque identifier for the credential (logged, not
///                        used cryptographically here).
/// - `signature`        — the holder's BBS+ signature over `messages`.
/// - `vk`               — the issuer's verifying key.
/// - `messages`         — the full, signed message vector.
/// - `disclosed_indices`— the subset of message indices to reveal.
/// - `nonce`            — a 32-byte verifier-supplied nonce; MUST be fresh
///                        per session.
///
/// # Returns
/// An `UnlinkableDisclosure` containing the proof bytes and the bound nonce.
#[cfg(feature = "std")]
pub fn create_unlinkable_disclosure<R: rand::RngCore>(
    rng: &mut R,
    credential_id: &[u8],
    signature: &BbsSignature,
    vk: &VerifyingKey,
    messages: &[Fr],
    disclosed_indices: &[u32],
    nonce: &[u8; 32],
) -> BbsResult<UnlinkableDisclosure> {
    let proof = BbsPresentation::create_presentation(
        rng,
        signature,
        vk,
        messages,
        disclosed_indices,
        nonce as &[u8],
    )?;

    let mut sorted_indices: Vec<u32> = disclosed_indices.to_vec();
    sorted_indices.sort_unstable();
    sorted_indices.dedup();

    Ok(UnlinkableDisclosure {
        proof_bytes: proof.to_bytes(),
        nonce: *nonce,
        credential_id: credential_id.to_vec(),
        disclosed_indices: sorted_indices,
    })
}

/// Verify an unlinkable selective-disclosure proof.
///
/// Checks:
/// 1. The embedded nonce matches `expected_nonce` (replay protection).
/// 2. The cryptographic proof verifies against `vk` with the embedded nonce
///    as the presentation context.
///
/// # Returns
/// - `Ok(true)` — nonce matches and proof is cryptographically valid.
/// - `Ok(false)` — nonce matches but proof fails cryptographic verification.
/// - `Err(BbsError::NonceMismatch)` — the embedded nonce does not match
///   `expected_nonce` (possible replay attack or wrong session).
/// - `Err(...)` — other deserialization or arithmetic error.
pub fn verify_unlinkable_disclosure(
    disclosure: &UnlinkableDisclosure,
    vk: &VerifyingKey,
    expected_nonce: &[u8; 32],
) -> BbsResult<bool> {
    // Nonce check — must be constant-time to resist timing side-channels.
    if !constant_time_eq(&disclosure.nonce, expected_nonce) {
        return Err(BbsError::NonceMismatch);
    }

    let proof = disclosure.proof()?;
    BbsPresentation::verify_presentation(vk, &proof, &disclosure.nonce)
}

/// Constant-time equality for 32-byte slices.
///
/// Avoids early exit that could leak information about where nonces differ.
fn constant_time_eq(a: &[u8; 32], b: &[u8; 32]) -> bool {
    let mut diff = 0u8;
    for i in 0..32 {
        diff |= a[i] ^ b[i];
    }
    diff == 0
}

// ────────────────────────────────────────────────────────────────────────────
// Nonce registry for verifier-side session management

/// A simple nonce registry for verifiers.
///
/// The verifier generates a nonce per session (credential_id + session_id),
/// stores it here, and removes it after a successful or failed verification.
/// This prevents the same nonce being accepted twice (nonce reuse attack).
pub struct NonceRegistry {
    /// (credential_id, session_id) → nonce
    store: BTreeMap<(Vec<u8>, Vec<u8>), [u8; 32]>,
}

impl NonceRegistry {
    pub fn new() -> Self {
        NonceRegistry {
            store: BTreeMap::new(),
        }
    }

    /// Register a nonce for a (credential_id, session_id) pair.
    ///
    /// Overwrites any prior entry for the same pair.
    pub fn register(&mut self, credential_id: &[u8], session_id: &[u8], nonce: [u8; 32]) {
        self.store
            .insert((credential_id.to_vec(), session_id.to_vec()), nonce);
    }

    /// Retrieve a previously registered nonce, removing it from the registry
    /// (consume-once semantics prevent nonce reuse).
    pub fn consume(&mut self, credential_id: &[u8], session_id: &[u8]) -> Option<[u8; 32]> {
        self.store
            .remove(&(credential_id.to_vec(), session_id.to_vec()) as &(Vec<u8>, Vec<u8>))
    }

    /// Number of pending (unconsumed) nonces.
    pub fn pending_count(&self) -> usize {
        self.store.len()
    }
}

impl Default for NonceRegistry {
    fn default() -> Self {
        Self::new()
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::signature::BbsSignature;
    use crate::{SigningKey, VerifyingKey};
    use alloc::vec;
    use rand::rngs::StdRng;
    use rand::SeedableRng;

    fn rng() -> StdRng {
        StdRng::seed_from_u64(1337)
    }

    fn setup(n: u32) -> (SigningKey, VerifyingKey, Vec<Fr>) {
        let mut r = rng();
        let sk = SigningKey::generate(&mut r);
        let vk = VerifyingKey::derive(sk.public_key(), b"linkability-test", n).unwrap();
        let messages: Vec<Fr> = (0..n).map(|i| Fr::from_u64(i as u64 + 10)).collect();
        (sk, vk, messages)
    }

    fn make_nonce(seed: u8) -> [u8; 32] {
        let mut r = StdRng::seed_from_u64(seed as u64);
        generate_nonce_with_rng(&mut r).unwrap()
    }

    // ── basic create/verify ──────────────────────────────────────────────

    #[test]
    fn test_create_and_verify_unlinkable_disclosure() {
        let (sk, vk, messages) = setup(3);
        let mut r = rng();
        let sig = BbsSignature::sign(&mut r, &sk, &vk, &messages).unwrap();
        let nonce = make_nonce(1);

        let disclosure = create_unlinkable_disclosure(
            &mut r,
            b"cred-1",
            &sig,
            &vk,
            &messages,
            &[1],
            &nonce,
        )
        .unwrap();

        let result = verify_unlinkable_disclosure(&disclosure, &vk, &nonce).unwrap();
        assert!(result);
    }

    #[test]
    fn test_verify_rejects_wrong_nonce() {
        let (sk, vk, messages) = setup(2);
        let mut r = rng();
        let sig = BbsSignature::sign(&mut r, &sk, &vk, &messages).unwrap();
        let nonce = make_nonce(2);
        let wrong_nonce = make_nonce(99);

        let disclosure = create_unlinkable_disclosure(
            &mut r, b"cred-x", &sig, &vk, &messages, &[0], &nonce,
        )
        .unwrap();

        let err = verify_unlinkable_disclosure(&disclosure, &vk, &wrong_nonce);
        assert!(matches!(err, Err(BbsError::NonceMismatch)));
    }

    // ── unlinkability ─────────────────────────────────────────────────────

    #[test]
    fn test_two_disclosures_with_different_nonces_are_unlinkable() {
        let (sk, vk, messages) = setup(2);
        let mut r = rng();
        let sig = BbsSignature::sign(&mut r, &sk, &vk, &messages).unwrap();

        let nonce1 = make_nonce(10);
        let nonce2 = make_nonce(11);

        let d1 = create_unlinkable_disclosure(
            &mut r, b"cred-2", &sig, &vk, &messages, &[0], &nonce1,
        )
        .unwrap();
        let d2 = create_unlinkable_disclosure(
            &mut r, b"cred-2", &sig, &vk, &messages, &[0], &nonce2,
        )
        .unwrap();

        // Proofs must differ; same underlying credential but fresh randomness.
        assert_ne!(d1.proof_bytes, d2.proof_bytes);
        assert_ne!(d1.nonce, d2.nonce);

        // Both should verify against their own nonces.
        assert!(verify_unlinkable_disclosure(&d1, &vk, &nonce1).unwrap());
        assert!(verify_unlinkable_disclosure(&d2, &vk, &nonce2).unwrap());
    }

    #[test]
    fn test_two_disclosures_with_same_nonce_produce_different_proofs() {
        // Even with the same nonce, r1/r2 randomization ensures A_bar differs.
        let (sk, vk, messages) = setup(1);
        let mut r = rng();
        let sig = BbsSignature::sign(&mut r, &sk, &vk, &messages).unwrap();
        let nonce = make_nonce(20);

        let d1 = create_unlinkable_disclosure(
            &mut r, b"cred-3", &sig, &vk, &messages, &[], &nonce,
        )
        .unwrap();
        let d2 = create_unlinkable_disclosure(
            &mut r, b"cred-3", &sig, &vk, &messages, &[], &nonce,
        )
        .unwrap();

        assert_ne!(d1.proof_bytes, d2.proof_bytes);
    }

    // ── nonce registry ────────────────────────────────────────────────────

    #[test]
    fn test_nonce_registry_register_and_consume() {
        let mut registry = NonceRegistry::new();
        let nonce = make_nonce(30);
        registry.register(b"cred-1", b"session-1", nonce);
        assert_eq!(registry.pending_count(), 1);

        let consumed = registry.consume(b"cred-1", b"session-1");
        assert_eq!(consumed, Some(nonce));
        assert_eq!(registry.pending_count(), 0);
    }

    #[test]
    fn test_nonce_registry_consume_once_semantics() {
        let mut registry = NonceRegistry::new();
        let nonce = make_nonce(31);
        registry.register(b"cred-x", b"session-x", nonce);

        let first = registry.consume(b"cred-x", b"session-x");
        let second = registry.consume(b"cred-x", b"session-x");
        assert!(first.is_some());
        assert!(second.is_none()); // nonce was consumed; cannot reuse
    }

    #[test]
    fn test_nonce_registry_overwrite() {
        let mut registry = NonceRegistry::new();
        let n1 = make_nonce(40);
        let n2 = make_nonce(41);
        registry.register(b"cred", b"sess", n1);
        registry.register(b"cred", b"sess", n2);
        assert_eq!(registry.pending_count(), 1);
        assert_eq!(registry.consume(b"cred", b"sess"), Some(n2));
    }

    // ── serialization roundtrip ───────────────────────────────────────────

    #[test]
    fn test_unlinkable_disclosure_serialization_roundtrip() {
        let (sk, vk, messages) = setup(2);
        let mut r = rng();
        let sig = BbsSignature::sign(&mut r, &sk, &vk, &messages).unwrap();
        let nonce = make_nonce(50);

        let d = create_unlinkable_disclosure(
            &mut r, b"cred-ser", &sig, &vk, &messages, &[1], &nonce,
        )
        .unwrap();

        let bytes = d.to_bytes();
        let d2 = UnlinkableDisclosure::from_bytes(&bytes).unwrap();

        assert_eq!(d.nonce, d2.nonce);
        assert_eq!(d.credential_id, d2.credential_id);
        assert_eq!(d.disclosed_indices, d2.disclosed_indices);
        assert_eq!(d.proof_bytes, d2.proof_bytes);
        // Verify the deserialized version still passes.
        assert!(verify_unlinkable_disclosure(&d2, &vk, &nonce).unwrap());
    }

    // ── nonce generation ──────────────────────────────────────────────────

    #[test]
    fn test_generate_nonce_produces_32_bytes() {
        let mut r = StdRng::seed_from_u64(99);
        let n = generate_nonce_with_rng(&mut r).unwrap();
        assert_eq!(n.len(), 32);
    }

    #[test]
    fn test_generate_nonce_is_not_all_zeros() {
        let mut r = StdRng::seed_from_u64(100);
        let n = generate_nonce_with_rng(&mut r).unwrap();
        assert_ne!(n, [0u8; 32]);
    }

    #[test]
    fn test_two_generated_nonces_differ() {
        let mut r = StdRng::seed_from_u64(101);
        let n1 = generate_nonce_with_rng(&mut r).unwrap();
        let n2 = generate_nonce_with_rng(&mut r).unwrap();
        assert_ne!(n1, n2);
    }

    // ── constant_time_eq ─────────────────────────────────────────────────

    #[test]
    fn test_constant_time_eq_equal() {
        let a = [0xABu8; 32];
        let b = [0xABu8; 32];
        assert!(constant_time_eq(&a, &b));
    }

    #[test]
    fn test_constant_time_eq_unequal() {
        let a = [0u8; 32];
        let mut b = [0u8; 32];
        b[31] = 1;
        assert!(!constant_time_eq(&a, &b));
    }
}
